"""Build the machine-readable catalog, GEO metadata, and GitHub Pages site.

The output is deterministic: the same repository state always renders the same
bytes, so ``--check`` can fail CI when the committed distribution document
drifts from the released Skill suite.
"""

from __future__ import annotations

import argparse
from html import escape
import json
from pathlib import Path
import shutil
import sys

from distribution import ROOT, build_catalog, load_manifest


DEFAULT_OUTPUT = ROOT / "site"
DISTRIBUTION_DOC = ROOT / "docs" / "DISTRIBUTION.md"
GENERATED_NOTE = "<!-- Generated by scripts/build_geo_site.py. Do not edit by hand. -->"


def _page(base_url: str, title: str, description: str, jsonld: dict, body: str) -> str:
    """Render one static page: no scripts, no external assets, one JSON-LD block."""
    url = jsonld.get("url", base_url)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<meta name="description" content="{escape(description)}">
<link rel="canonical" href="{escape(url)}">
<meta property="og:type" content="website">
<meta property="og:title" content="{escape(title)}">
<meta property="og:description" content="{escape(description)}">
<meta property="og:url" content="{escape(url)}">
<meta name="twitter:card" content="summary">
<style>
:root {{ color-scheme: light dark; }}
body {{ margin: 0 auto; max-width: 46rem; padding: 2rem 1rem 4rem;
  font: 16px/1.65 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }}
code, pre {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; }}
pre {{ overflow-x: auto; padding: 0.75rem 1rem; border-radius: 6px;
  background: rgba(127, 127, 127, 0.14); }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border-bottom: 1px solid rgba(127, 127, 127, 0.35); padding: 0.4rem 0.5rem;
  text-align: left; vertical-align: top; }}
</style>
<script type="application/ld+json">
{json.dumps(jsonld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
{body}
</body>
</html>
"""


def _software_application(catalog: dict, skill: dict | None = None) -> dict:
    target = skill or catalog
    name = f"{catalog['name']} - {skill['slug']}" if skill else catalog["name"]
    return {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": name,
        "alternateName": skill["slug"] if skill else "dcc-mcp-agent-plugins",
        "description": target["description"],
        "url": skill["page_url"] if skill else catalog["homepage"],
        "applicationCategory": "DeveloperApplication",
        "applicationSubCategory": "AI Agent Skill",
        "operatingSystem": "Windows, macOS, Linux",
        "softwareVersion": target["version"],
        "license": f"https://spdx.org/licenses/{target['license']}.html",
        "codeRepository": skill["source_url"] if skill else catalog["repository"],
        "keywords": ", ".join((skill or catalog)["keywords"]),
        "isAccessibleForFree": True,
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "author": {
            "@type": "Organization",
            "name": catalog["publisher"]["name"],
            "url": catalog["publisher"]["url"],
        },
        "publisher": {
            "@type": "Organization",
            "name": catalog["publisher"]["name"],
            "url": catalog["publisher"]["url"],
        },
    }


def _index_body(catalog: dict) -> str:
    rows = "\n".join(
        f'<tr><td><a href="skills/{escape(skill["slug"])}.html"><code>{escape(skill["slug"])}</code></a></td>'
        f"<td>{escape(skill['description'])}</td></tr>"
        for skill in catalog["skills"]
    )
    channels = "\n".join(
        f'<tr><td><a href="{escape(channel["url"])}">{escape(channel["name"])}</a></td>'
        f"<td>{escape(channel['automation'])}</td><td>{escape(channel['notes'])}</td></tr>"
        for channel in catalog["channels"]
    )
    return f"""<h1>{escape(catalog["name"])}</h1>
<p>{escape(catalog["description"])}</p>
<p>Version <strong>{escape(catalog["version"])}</strong> &middot;
<a href="{escape(catalog["repository"])}">Source</a> &middot;
<a href="catalog.json">catalog.json</a> &middot;
<a href="llms.txt">llms.txt</a> &middot;
<a href="llms-full.txt">llms-full.txt</a></p>
<h2>Install</h2>
<pre><code>{escape(catalog["install"]["skills_cli"])}</code></pre>
<p>Or vendor the same canonical Skills through npm:</p>
<pre><code>{escape(catalog["install"]["npm"])}</code></pre>
<h2>Skills</h2>
<table><thead><tr><th>Skill</th><th>What it does</th></tr></thead><tbody>
{rows}
</tbody></table>
<h2>Distribution channels</h2>
<table><thead><tr><th>Channel</th><th>Automation</th><th>Notes</th></tr></thead><tbody>
{channels}
</tbody></table>
"""


def _skill_body(catalog: dict, skill: dict) -> str:
    installs = "\n".join(
        f"<h3>{escape(label)}</h3><pre><code>{escape(command)}</code></pre>"
        for label, command in (
            ("Agent Skills CLI", skill["install"]["skills_cli"]),
            ("ClawHub", skill["install"]["clawhub"]),
            ("npm", skill["install"]["npm"]),
        )
    )
    tags = ", ".join(escape(tag) for tag in skill["tags"]) or "&mdash;"
    return f"""<p><a href="../index.html">&larr; {escape(catalog["name"])}</a></p>
<h1><code>{escape(skill["slug"])}</code></h1>
<p>{escape(skill["description"])}</p>
<p>Version <strong>{escape(skill["version"])}</strong> &middot;
License {escape(skill["license"])} &middot;
<a href="{escape(skill["source_url"])}">SKILL.md source</a></p>
<h2>Install</h2>
{installs}
<h2>Tags</h2>
<p>{tags}</p>
"""


def _llms_txt(catalog: dict) -> str:
    lines = [
        f"# {catalog['name']}",
        "",
        f"> {catalog['description']} Version {catalog['version']}, MIT-licensed, "
        "installable into Claude Code, Codex, Cursor, Gemini CLI, GitHub Copilot, "
        "Windsurf, OpenCode, Cline, Roo Code, Kiro, Amp, and other Agent Skills hosts.",
        "",
        f"Install the default Skill: `{catalog['install']['skills_cli']}`",
        "",
        "## Skills",
        "",
    ]
    lines += [f"- [{skill['slug']}]({skill['page_url']}): {skill['description']}" for skill in catalog["skills"]]
    lines += ["", "## Sources", ""]
    lines += [
        f"- [{skill['slug']} SKILL.md]({skill['skill_md_url']}): canonical instructions"
        for skill in catalog["skills"]
    ]
    lines += [
        "",
        "## Optional",
        "",
        f"- [Repository]({catalog['repository']}): source, marketplace manifests, and release archives",
        f"- [catalog.json]({catalog['homepage']}/catalog.json): machine-readable Skill and channel metadata",
        f"- [llms-full.txt]({catalog['homepage']}/llms-full.txt): every SKILL.md concatenated in full",
        "",
    ]
    return "\n".join(lines)


def _llms_full_txt(catalog: dict, root: Path) -> str:
    chunks = [
        f"# {catalog['name']} {catalog['version']}",
        "",
        catalog["description"],
        "",
        f"Source: {catalog['repository']}",
        f"Install: {catalog['install']['skills_cli']}",
        "",
    ]
    for skill in catalog["skills"]:
        body = (root / skill["source_path"] / "SKILL.md").read_text(encoding="utf-8")
        chunks += [
            "---",
            "",
            f"## Skill: {skill['slug']}",
            "",
            f"Source: {skill['skill_md_url']}",
            "",
            body.strip(),
            "",
        ]
    return "\n".join(chunks) + "\n"


def _robots_txt(catalog: dict, crawlers: list[str]) -> str:
    lines = ["User-agent: *", "Allow: /", ""]
    for crawler in crawlers:
        lines += [f"User-agent: {crawler}", "Allow: /", ""]
    lines.append(f"Sitemap: {catalog['homepage']}/sitemap.xml")
    return "\n".join(lines) + "\n"


def _sitemap(catalog: dict) -> str:
    urls = [catalog["homepage"] + "/", *(skill["page_url"] for skill in catalog["skills"])]
    entries = "\n".join(f"  <url><loc>{escape(url)}</loc></url>" for url in urls)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def _distribution_doc(catalog: dict) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        "# Distribution channels",
        "",
        f"Released version: **{catalog['version']}** &middot; Catalog: `{catalog['homepage']}/catalog.json`",
        "",
        "| Channel | Kind | Automation | Notes |",
        "| --- | --- | --- | --- |",
    ]
    for channel in catalog["channels"]:
        notes = channel["notes"].replace("|", "\\|")
        lines.append(
            f"| [{channel['name']}]({channel['url']}) | {channel['kind']} | {channel['automation']} | {notes} |"
        )
    lines += [
        "",
        "`published` channels run from `.github/workflows/release.yml` on a `v*` tag.",
        "`verified` channels are checked against the public repository but expose no publish API.",
        "`manual` channels need a human submission; the entries below are regenerated from",
        "the released Skill suite so a submission never quotes stale metadata.",
        "",
        "## Directory submission entries",
        "",
    ]
    for skill in catalog["skills"]:
        lines += [
            f"### {skill['slug']}",
            "",
            f"- **Name**: {skill['slug']}",
            f"- **Version**: {skill['version']}",
            f"- **Repository**: {catalog['repository']}",
            f"- **Skill URL**: {skill['source_url']}",
            f"- **Install**: `{skill['install']['skills_cli']}`",
            f"- **Description**: {skill['description']}",
            f"- **Tags**: {', '.join(skill['tags']) or '-'}",
            "",
        ]
    return "\n".join(lines)


def build(output: Path, root: Path = ROOT) -> dict:
    catalog = build_catalog(root)
    crawlers = load_manifest()["site"]["ai_crawlers"]
    base_url = catalog["homepage"]

    if output.exists():
        shutil.rmtree(output)
    (output / "skills").mkdir(parents=True)

    (output / ".nojekyll").write_text("", encoding="utf-8")
    (output / "catalog.json").write_text(
        json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (output / "llms.txt").write_text(_llms_txt(catalog), encoding="utf-8")
    (output / "llms-full.txt").write_text(_llms_full_txt(catalog, root), encoding="utf-8")
    (output / "robots.txt").write_text(_robots_txt(catalog, crawlers), encoding="utf-8")
    (output / "sitemap.xml").write_text(_sitemap(catalog), encoding="utf-8")

    index_ld = _software_application(catalog)
    index_ld["hasPart"] = [
        {
            "@type": "SoftwareApplication",
            "name": skill["slug"],
            "url": skill["page_url"],
            "softwareVersion": skill["version"],
        }
        for skill in catalog["skills"]
    ]
    (output / "index.html").write_text(
        _page(base_url, catalog["name"], catalog["description"], index_ld, _index_body(catalog)),
        encoding="utf-8",
    )
    for skill in catalog["skills"]:
        (output / "skills" / f"{skill['slug']}.html").write_text(
            _page(
                base_url,
                f"{skill['slug']} - {catalog['name']}",
                skill["description"],
                _software_application(catalog, skill),
                _skill_body(catalog, skill),
            ),
            encoding="utf-8",
        )
    return catalog


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the GEO catalog and GitHub Pages site")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail when docs/DISTRIBUTION.md is stale")
    args = parser.parse_args()

    try:
        catalog = build(args.output)
        rendered = _distribution_doc(catalog)
        if args.check:
            current = DISTRIBUTION_DOC.read_text(encoding="utf-8") if DISTRIBUTION_DOC.is_file() else ""
            if current != rendered:
                print("docs/DISTRIBUTION.md is stale; run python scripts/build_geo_site.py", file=sys.stderr)
                return 1
        else:
            DISTRIBUTION_DOC.parent.mkdir(parents=True, exist_ok=True)
            DISTRIBUTION_DOC.write_text(rendered, encoding="utf-8")
        print(f"Built {len(catalog['skills'])} Skill pages and GEO metadata at {args.output}")
        return 0
    except (KeyError, OSError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
